//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 11:34:34 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "jabber:client",
    elementFormDefault = XmlNsForm.UNQUALIFIED,
    xmlns = {@XmlNs(prefix = "", namespaceURI = "jabber:client")})
package com.expleague.xmpp.stanza;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;