platform :ios, '8.0'

use_frameworks!

target 'unSearch' do
  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
  pod 'MMMarkdown'
  pod 'ReachabilitySwift'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
#  pod 'SDCAlertView', '~> 5.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

