platform :ios, '8.0'

use_frameworks!

def commonPods
  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
  pod 'ReachabilitySwift'
end

target 'unSearch' do
  commonPods
  pod 'BNHtmlPdfKit', :git => 'https://github.com/brentnycum/BNHtmlPdfKit'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'FacebookCore', '~> 0.2'
  pod 'FacebookLogin', '~> 0.2'
  pod 'FacebookShare', '~> 0.2'
  pod 'FBSDKCoreKit', '~> 4.22.1'
  pod 'FBSDKLoginKit', '~> 4.22.1'
  pod 'FBSDKShareKit', '~> 4.22.1'
end

target 'unSearchCore' do
  commonPods
  pod 'MMMarkdown'
end

target 'SiriOrderHandler' do
  commonPods
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end

