//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.12 at 12:05:07 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jabber.org/protocol/disco#info", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package com.tbts.xmpp.control.discovery;
